theme: jekyll-theme-minimal
title: [这个世界会好吗？]
description: [The webpage you are looking at is a new way for me to connect and communicate with the other, reflecting some parts of me.]
logo: /assets/img/IMG_1717.JPG
